language: ruby
cache: bundler
rvm:
  - 2.1.2

env:
  - DB=postgresql

before_script:
  - psql -c 'create database jerky_test' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
